export const TASK_NEW = 'TASK_NEW';
export const TASK_IN_PROGRESS = 'TASK_IN_PROGRESS';
export const TASK_FAILED = 'TASK_FAILED';
export const TASK_COMPLETE = 'TASK_COMPLETE';
export const TASK_DOWNLOADED = 'TASK_DOWNLOADED';
export const TASK_DELETED = 'TASK_DELETED';