const TaskStates = {
    TASK_NEW: 'TASK_NEW',
    TASK_IN_PROGRESS: 'TASK_IN_PROGRESS',
    TASK_FAILED: 'TASK_FAILED',
    TASK_COMPLETE: 'TASK_COMPLETE',
    TASK_DOWNLOADED: 'TASK_DOWNLOADED',
    TASK_DELETED: 'TASK_DELETED',
};

module.exports = TaskStates;